name: Keep Render Awake

on:
  schedule:
    # Run every 5 minutes to prevent Render free tier sleep
    - cron: "*/5 * * * *"
  # Allow manual trigger
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping health endpoint
        env:
          HEALTH_URL: ${{ secrets.RENDER_HEALTH_URL }}
        run: |
          if [ -z "$HEALTH_URL" ]; then
            echo "Missing RENDER_HEALTH_URL secret (e.g. https://your-app.onrender.com/health).";
            exit 1;
          fi
          echo "Pinging $HEALTH_URL"
          # Fail the workflow on any error; keep request lightweight
          curl -fsS --max-time 10 "$HEALTH_URL" >/dev/null
